### ISSUE TITLE
App2 missing database

### ISSUE THREAD

**Issue by dzink** [ProboCI/probo#216]
I sent a client a link about a week ago for review. She logged in and made some changes (I know, I know) for me to look at. When I tried to log in last night, the database was presumably gone because I was sent to the drupal install page.

**Comment by dzink** [comment]
Update: It looks like actually certain parts of the builds do not wake up on time, but they do actually wake up. I'm seeing this on a few other builds. Here was the error I got this time.

This happened on two different builds, with the first I wasn't sure if it was running something in the shell that woke it up, or if it was just a matter of time. With the second, I waited only and eventually it came online.

```
[Mon Feb 07 14:46:38.766498 2022] [php7:notice] [pid 384] [client 172.17.0.1:49716] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /src/docroot/core/
lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /src/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(190): PDO->__constru
ct()\n#1 /src/docroot/core/lib/Drupal/Core/Database/Database.php(387): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open()\n#2 /src/docroot/core/lib/Drupal/Core/D
atabase/Database.php(169): Drupal\\Core\\Database\\Database::openConnection()\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection()\n#4 /src/docroo
t/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()\n#5 /src/docroot/core/lib/Drupal/Component/DependencyInjection/Contain
er.php(176): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService()\n#6 /src/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer
.php(212): Drupal\\Component\\DependencyInjection\\Container->get()\n#7 /src/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Co
mponent\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters()\n#8 /src/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupa
l\\Component\\DependencyInjection\\PhpArrayContainer->createService()\n#9 /src/docroot/core/lib/Drupal/Core/DrupalKernel.php(549): Drupal\\Component\\DependencyInjectio
n\\Container->get()\n#10 /src/docroot/core/lib/Drupal/Core/DrupalKernel.php(894): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /src/docroot/core/lib/
Drupal/Core/DrupalKernel.php(472): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /src/docroot/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalK
ernel->boot()\n#13 /src/docroot/index.php(19): Drupal\\Core\\DrupalKernel->handle()\n#14 {main}, referer: https://app2.probo.ci/
```

**Comment by dzink** [comment]
Also the error on the screen that clients see is "The website encountered an unexpected error. Please try again later."

**Comment by dzink** [comment]
Update: looks like the performance tweaks made a huge improvement. I still got this error on both builds I tried to open today, but it only took one refresh and they were up

**Comment by ElusiveMind** [comment]
This is due to the database server waking up after the web server. We're working on a resolution to this in terms of a persistent database that lives outside of containers.[
